// @ts-check
import { defineConfig } from 'astro/config';

// sitemap.xml, robots.txt, llms.txt and llms-full.txt are generated by endpoints in src/pages/
// from the route registry in src/lib/seo.ts (noindex pages and /app are excluded there).
export default defineConfig({
  site: 'https://thosjod.com',
  trailingSlash: 'ignore',
  image: { domains: ['images.unsplash.com'] },
  redirects: {
    // application-ia-ux-copy.md: "/app - Redirects authenticated users to /app/dashboard"
    '/app': '/app/dashboard',
    // 02-sitemap planned this URL; the content lives at /compare/thosjod-vs-warmly
    '/compare/visitor-identification-tools': '/compare/thosjod-vs-warmly',
  },
});
