// @ts-check
import { defineConfig } from 'astro/config';

// sitemap.xml, robots.txt, llms.txt and llms-full.txt are generated by endpoints in src/pages/
// from the route registry in src/lib/seo.ts (noindex pages and /app are excluded there).
export default defineConfig({
  site: 'https://thosjod.com',
  trailingSlash: 'ignore',
  image: { domains: ['images.unsplash.com'] },
  redirects: {
    // /app lands on the assistants list (the app's home)
    '/app': '/app/assistants',
    // 02-sitemap planned this URL; the content lives at /compare/thosjod-vs-warmly
    '/compare/visitor-identification-tools': '/compare/thosjod-vs-warmly',
  },
});
